### ISSUE TITLE
ZBClient.updateWorkflowInstancePayload fails.

### ISSUE THREAD

**Issue by butlera1** [CreditSenseAU/zeebe-client-node-js#10]
ZBClient.updateWorkflowInstancePayload fails to execute due to a misspelled function call.

`public updateWorkflowInstancePayload(request: ZB.UpdateWorkflowInstancePayloadRequest): Promise<void> {
        return this.gRPCClient.updateWorkflowInstancePayloadRequestSync(stringifyPayload(request));
    }
`

This method above (see ZBClient.js) calls "this.gRPCClient.updateWorkflowInstancePayloadRequestSync" and I believe it should be "this.gRPCClient.updateWorkflowInstancePayloadSync".

**Comment by jwulf** [comment]
Thanks for reporting this @butlera1 - looking in to it now.

**Comment by jwulf** [comment]
This has changed: https://github.com/zeebe-io/zeebe/pull/2084

```BREAKING CHANGE:

renames UpdateWorkflowInstancePayload to SetVariables
renames UpdatePayloadCommand to SetVariablesCommand```

**Comment by jwulf** [comment]
OK, making the change to `setVariables` is relatively straight-forward, and I've done that.

However, no jobs are streaming to the client with the 0.17.0 server. This is blocked by https://github.com/CreditSenseAU/zeebe-client-node-js/issues/15.

**Comment by jwulf** [comment]
This is fixed by https://github.com/CreditSenseAU/zeebe-client-node-js/pull/16
