### ISSUE TITLE
Update complete syntax in README

### ISSUE THREAD

**Issue by tvvignesh** [creditsenseau/zeebe-client-node-js#104]
Hi. The README suggests to use `complete()` to complete a task worker while such a function is not defined. Rather `complete.success` and `complete.failure` are to be used as suggested in README again.

It might need to be updated. Thanks.

**Comment by jwulf** [comment]
Thanks! Updated here: https://github.com/creditsenseau/zeebe-client-node-js#completing-tasks-with-success-or-failure
