### ISSUE TITLE
Service Task followed by Message Catch Events

### ISSUE THREAD

**Issue by tvvignesh** [creditsenseau/zeebe-client-node-js#105]
Hi. I was testing few things and found a strange bug. When we have a service task followed by a message catch event like given in the screenshot below, and if I use  `complete.success(updatedWorkflowObj)` to complete the worker followed by `publishMessage()` immediately in succession, the message catch event is not received by Zeebe.

I have to rather add a setTimeOut or delay before I do publishMessage() to the workflow post complete.success. 

My assumption here is that the workflow receives the message event faster than it receives the task complete event (not sure though). Are the protocols used for both message catch event as well as task worker completion the same? If yes, may I know if the order in which such events are published are preserved/queued?

![Screenshot from 2019-11-14 18-59-14](https://user-images.githubusercontent.com/1165845/68861114-e15c1180-0710-11ea-8a9f-24a72dd4e5ec.png)

**Comment by jwulf** [comment]
The message subscription in this case is created when the token hits the catch event. Publish the message with a TTL, or put this in a sub-process. See the last two sections here: https://zeebe.io/blog/2019/08/zeebe-message-correlation/
