### ISSUE TITLE
OAuth cache directory might be not writable

### ISSUE THREAD

**Issue by MainAero** [creditsenseau/zeebe-client-node-js#110]
The [cacheDir](https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/lib/OAuthProvider.ts#L27) of the OAuthProvider is not writable in some environments.

We are running this zeebe client in AWS Lambda which doesn't allow to write to the home directory. This results in a flood of token requests.
If `cacheOnDisk` option is set to `true` I would expect an fatal exception if the cache directory is not writable. As well a good option would be to make the `cacheDir` configurable.

**Our workaround:**
- Set the `HOME` environment variable of your lambda function to `/tmp` (which is by default writable)

**Comment by jwulf** [comment]
Can you check your logs? It should log errors - https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/lib/OAuthProvider.ts#L137

That deep, throwing won't halt anything. I could check it in the ConfigurationHydrator at startup...

**Comment by jwulf** [comment]
Easiest to throw for now. That should halt all action if I do it in the oAuthProvider constructor.
