### ISSUE TITLE
Is "OperationOptions" used ?

### ISSUE THREAD

**Issue by OlivierAlbertini** [creditsenseau/zeebe-client-node-js#125]
Hello fellow developers,

I'm working on [Workit](https://github.com/VilledeMontreal/workit) in order to be compatible with the latest and the greatest version of this library.
I jump from `0.20.1` to `0.22.1`
Looking at:
https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/lib/interfaces.ts#L39-L53

It seems not used since the recent release:

> The signature for specifying a workflow definition version in createWorkflowInstance has changed. See the README for the new signature.

am I wrong ? 

Let me know! I can make a PR to remove interfaces as well.

**Comment by jwulf** [comment]
Here are the new method overloads: https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/zb/ZBClient.ts#L248

It looks like the operation options need to be set in the constructor.

**Comment by OlivierAlbertini** [comment]
Thanks!
