### ISSUE TITLE
Error when using createWorkflowInstanceWithResult

### ISSUE THREAD

**Issue by IamManifold** [creditsenseau/zeebe-client-node-js#126]
working through this tutorial, https://zeebe.joshwulf.com/quickstart/quickstart/
getting to the point where i change update createWorkflowInstance to  createWorkflowInstanceWithResult.

I'm receive this error after a few seconds of running it with "createWorkflowInstanceWithResult".

```
> Error: 13 INTERNAL: Unexpected error occurred during the request processing
    at Object.exports.createStatusError (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\common.js:91:15)
    at Object.onReceiveStatus (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:1209:28)
    at InterceptingListener._callNext (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:568:42)
    at InterceptingListener.onReceiveStatus (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:618:8)
    at callback (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:847:24) {
  code: 13,
  metadata: Metadata { _internal_repr: {}, flags: 0 },
  details: 'Unexpected error occurred during the request processing'
```

I'm presuming it's from not receiving a response but idk for sure. 
Below is my worker code. 

```
> zbc.createWorker(null, "ImageInspection", (job, complete) => {
  console.log(JSON.stringify(job, null, 2))
  try {
      const readimage = 'c:\\images'
      const imageid = '123423'
      complete.success({
          readimage
      })
  } catch (e) {
      console.error("Something went wrong!")
      console.error(e)
      complete.fail(e.message)
  }
});
```

which is responding this

```
{
  "key": "2251799813693006",
  "type": "ImageInspection",
  "workflowInstanceKey": "2251799813692999",
  "bpmnProcessId": "Test_Yolo_workflow",
  "workflowDefinitionVersion": 4,
  "workflowKey": "2251799813692753",
  "elementId": "ReadImage",
  "elementInstanceKey": "2251799813693005",
  "customHeaders": {
    "propVideoFilepath": "VideoFilepath"
  },
  "worker": "52b33f3f-1af1-46b8-975a-57f36463f6cf",
  "retries": 3,
  "deadline": "1581962956672",
  "variables": {
    "readimage": "",
    "readvideo": ""
  }
}
```

**Comment by jwulf** [comment]
Yes, it is. See the note here: https://github.com/creditsenseau/zeebe-client-node-js#start-a-workflow-instance-and-await-the-workflow-outcome

See also here: https://github.com/zeebe-io/zeebe/issues/3699

**Comment by jwulf** [comment]
Please let me know if raising the timeout fixes this for you.

**Comment by IamManifold** [comment]
Receiving the same error with the code below, 

> const { ZBClient } = require('zeebe-node')
> const zbc = new ZBClient()
> 
> async function main() {
>     try {
>         await zbc.deployWorkflow('./workflow/yolotest.bpmn')
> 
>         let processId = 'Test_Yolo_workflow';
> 
>         const result = await zbc.createWorkflowInstanceWithResult({
>             bpmnProcessId: processId,
>             variables: {
>                 readimage: true,
>                 readvideo: "false",
>             },
>             requestTimeout: 25000,
>         })
> 
> 
>         console.log(JSON.stringify(result, null, 2))
>     } catch (e) {
>         console.error(e)
>     }
> }
> 
> main()

Error

> [nodemon] starting `node app.js index.js`
> Error: 13 INTERNAL: Unexpected error occurred during the request processing
>     at Object.exports.createStatusError (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\common.js:91:15)
>     at Object.onReceiveStatus (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:1209:28)
>     at InterceptingListener._callNext (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:568:42)
>     at InterceptingListener.onReceiveStatus (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:618:8)
>     at callback (C:\Zeebe\WorkerClient\Node\zeebeNodeClient\node_modules\grpc\src\client_interceptors.js:847:24) {
>   code: 13,
>   metadata: Metadata { _internal_repr: {}, flags: 0 },
>   details: 'Unexpected error occurred during the request processing'
> }

**Comment by jwulf** [comment]
Set the time out to 1000000 and try it again

**Comment by IamManifold** [comment]
Ok, i think that may have fixed the error. Should I be able to set up operate to view the status of my workflows and so on? I can log in but not sure where to config it, i'm sure there's a file or something i'm missing. 

I'm also missing something with my workers. 
I'm not sure what they are doing but i'm not showing anything about them marking a task complete  in the console

**First worker**
> const zb = require('zeebe-node')
> 
> ;(async () => {
> 	const zbc = new zb.ZBClient('127.0.0.1:26500')
> 	const topology = await zbc.topology()
> 	console.log(JSON.stringify(topology, null, 2))
> 
> 	
> 
> 	const zbWorker = zbc.createWorker('ImageInspection', 'ImageInspection', handler)
> 	setTimeout(() => {
> 		console.log('Closing client...')
> 		zbc.close().then(() => console.log('All workers closed'))
> 	}, 1000000)
> })()
> 
> function handler(payload, complete) {
> 	console.log('ZB payload', payload)
> 	complete.sucess(payload.variables,{ newvar:'bob'})
> }

RESPONSE

> {
>   "brokers": [
>     {
>       "partitions": [
>         {
>           "partitionId": 1,
>           "role": "LEADER"
>         }
>       ],
>       "nodeId": 0,
>       "host": "172.19.0.2",
>       "port": 26501
>     }
>   ],
>   "clusterSize": 1,
>   "partitionsCount": 1,
>   "replicationFactor": 1
> }
> {"timestamp":"2020-02-18T21:07:14.007Z","context":"C:\\Zeebe\\WorkerClient\\Node\\zeebeNodeClient\\node_modules\\zeebe-node\\dist\\zb\\ZBWorker.js:28","id":"ImageInspection","level":30,"message":"Ready for ImageInspection...","time":"2020 Feb-18 16:07:14PM","pollInterval":30000,"namespace":"ZBWorker","taskType":"ImageInspection"}


**second example of worker**
const { ZBClient } = require('zeebe-node')
const zbc = new ZBClient({
	onReady: () => console.log(`Connected!`),
	onConnectionError: () => console.log(`Disconnected!`)

zbc.createWorker("ImageInspection", "log", (job, complete) => {
    console.log(job);
    complete.success();
})

zbc.createWorker(null, "VideoInspection", (_, complete) => {
    complete.success({
        recommendation: "Video Inspection"
    })
})
**Second Response**

> C:\Zeebe\WorkerClient\Node\zeebeNodeClient>node worker.js
> {"timestamp":"2020-02-18T21:08:36.512Z","context":"C:\\Zeebe\\WorkerClient\\Node\\zeebeNodeClient\\node_modules\\zeebe-node\\dist\\zb\\ZBWorker.js:28","id":"ImageInspection","level":30,"message":"Ready for log...","time":"2020 Feb-18 16:08:36PM","pollInterval":30000,"namespace":"ZBWorker","taskType":"log"}
> {"timestamp":"2020-02-18T21:08:36.526Z","context":"C:\\Zeebe\\WorkerClient\\Node\\zeebeNodeClient\\node_modules\\zeebe-node\\dist\\zb\\ZBWorker.js:28","id":"6f512eb5-9590-443e-bb2e-ff6ff0db9957","level":30,"message":"Ready for VideoInspection...","time":"2020 Feb-18 16:08:36PM","pollInterval":30000,"namespace":"ZBWorker","taskType":"VideoInspection"}
> Connected!

**Comment by jwulf** [comment]
Use triple backticks to enclose code samples and console output to preserve formatting. 

Please use GitHub issues for reporting bugs and making feature requests. For helping hetting started and using the library, use Slack and the [Zeebe Forum](https://forum.zeebe.io).
