### ISSUE TITLE
Unexpected json-path token ROOT_OBJECT using latest server

### ISSUE THREAD

**Issue by cappelaere** [CreditSenseAU/zeebe-client-node-js#13]
Running on OSX
$ docker run -p 26500:26500 camunda/zeebe:latest
Then tried to load example workflow: $ node ./example/workflow.js
Server returns error:
23:37:43.757 [io.zeebe.gateway.impl.broker.BrokerRequestManager] [gateway-zb-actors-0] ERROR io.zeebe.gateway - Error handling gRPC request
io.grpc.StatusRuntimeException: INVALID_ARGUMENT: Command rejected with code 'CREATE': Expected to deploy new resources, but encountered the following validation errors:
'test.bpmn': - Element: Message_0ex7vc9 > extensionElements > subscription
    - ERROR: JSON path query is invalid: Unexpected json-path token ROOT_OBJECT

**Comment by jwulf** [comment]
Thanks for reporting this. I'll take a look. I'm in the process of realigning the library with the changes in 0.17.

**Comment by jwulf** [comment]
The cause of this is the replacement of JSON payloads with variables in 0.17.

What used to be a JSON path in bpmn files is now a variable, eg: `$.uniqueId` is now `uniqueId`. 

PR #16 fixes this and provides support for Zeebe 0.17.
