### ISSUE TITLE
Including zeebe-node module dramatically increases the app size and the build time

### ISSUE THREAD

**Issue by oguzeroglu** [creditsenseau/zeebe-client-node-js#138]
While integrating zeebe-client-node-js into Zeebe Modeler, we realized that it increases the app size by 77 MBs (on MacOS platform but similar in other platforms as well).

I've opened this issue in gRPC repo: https://github.com/grpc/grpc-node/issues/1283 as the dependency that takes the most space is gRPC. However I still wanted to let you guys know in case there's a way to optimize the build size or simply migrate to a lighter solution (if necessary/possible).

For the build time: Electron has issues with native modules come with the gRPC module, that's why we had to use the electron-rebuild tool, which increases the build time by around 5 minutes.

Best regards

**Comment by jwulf** [comment]
Yeah, that's life with gRPC, and life with binary modules and Electron. 

There is a [pure JS implementation of grpc](https://www.npmjs.com/package/@grpc/grpc-js), but I haven't tried it for a while.

I'll take a look at it again.

**Comment by oguzeroglu** [comment]
Thanks! I'll also try to experiment with this with a fork to see what happens!
