### ISSUE TITLE
Don't exec zeebe.topology() inside of constructor

### ISSUE THREAD

**Issue by nervgh** [creditsenseau/zeebe-client-node-js#151]
Hi everyone!

Thank you for this library :100: 

We are writing unit tests for our app. It looks like this:

**App.js**
```js
const ZB = require('zeebe-node')

// default export
module.exports = class App {
  constructor () {
    this.zeebe = new ZB.ZBClient()
  }
}
```

**App_spec.js**
```js
const App = require('./App')
const sinon = require('sinon')

describe('App', function () {)
  let app

  beforeEach(function () {
    app = new App()
    sinon.stub(app.zeebe, 'close')
    sinon.stub(app.zeebe, 'publishStartMessage')
  })

  it('should work', function () {
    // some code here
  })
})
```

And we got the error for each test case

> [topology]: 14 UNAVAILABLE: failed to connect to all addresses

because [that line](https://github.com/creditsenseau/zeebe-client-node-js/blob/master/src/zb/ZBClient.ts#L193). So we cannot stub it properly.

Could you disable `zeebe.topology()` inside of constructor? 
Or perhaps you show us how to stub it easily :smile: 

Thanks)

**Comment by jwulf** [comment]
Yeah, this was added to eagerly cause the connection to fail for an `onReady` event to be emitted for the Node-RED client.

One way to achieve this could be through an option that disables the eager connection.

**Comment by jwulf** [comment]
```
The ZBClient eagerly connects to the broker by issuing a topology command. This allows you an onReady event to be emitted. You can disable this (for example, for testing without a broker), by either passing `eagerConnection: false` to the client constructor options, or setting the environment variable `ZEEBE_NODE_EAGER_CONNECTION` to `false`.
```

**Comment by jwulf** [comment]
I am reversing this behaviour. Eager connection will be off by default, and will be able to be explicitly re-enabled.
