### ISSUE TITLE
Nodejs client should send the client type and version with his auth request

### ISSUE THREAD

**Issue by Zelldon** [creditsenseau/zeebe-client-node-js#155]
**Is your feature request related to a problem? Please describe.**

On camunda cloud we have sometimes bug reports / incidents which might be already fixed with the latest version of the client, but the user uses a old client version.

**Describe the solution you'd like**

We would like to detect the client type and version, on requesting the auth token. This would make incident investigation much easier, since we then don't need to ask the user for this kind of information if there went something wrong. It would also make it possible to correlate failures with know bugs.

We thought about adding this kind of information in the user agent header on the client HTTP request. 

**Describe alternatives you've considered**
The alternative would be to ask the user for this kind of information.

**Additional context**

The content of the user agent should at least contain:

 * client type, e.g. nodejs client
 * client version, e.g. 0.22.2

Related issues

 * https://github.com/zeebe-io/zeebe/issues/4265
 * https://github.com/zeebe-io/zeebe/issues/4264

**Comment by jwulf** [comment]
Fairly easy to do. Let me know the exact semantics and I'll add it.

**Comment by Zelldon** [comment]
I used in the c# client this format as user-agent value "client: <clienttype>, version: <version>"

**Comment by jwulf** [comment]
Added in 0.23.0
