### ISSUE TITLE
The latest version 0.23.0 miss dist directory

### ISSUE THREAD

**Issue by myfjdthink** [creditsenseau/zeebe-client-node-js#163]
run get error

> internal/modules/cjs/loader.js:324
>       throw err;
>       ^
> 
> Error: Cannot find module '/Users/nick/nodePro/zeebe-demo/node_modules/zeebe-node/dist/index.js'. Please verify that the package.json has a valid "main" entry

`ls node_modules/zeebe-node` to check the files, can't see dist directory, maybe was no build before publish to npm?

version 0.22.1 is fine

**Comment by MainAero** [comment]
In TS the line `import { ZBClient } from 'zeebe-node';` errors with `Cannot find module 'zeebe-node'.ts(2307)`.

**Comment by urbanisierung** [comment]
can confirm - since version `0.23.0-alpha1` the `dist` directory is missing

**Comment by jwulf** [comment]
That is... strange. It's built in CI, so that shouldn't happen.

I've published 0.23.1, and it has the `dist` directory in it.

**Comment by jwulf** [comment]
Belay that, it doesn't either....

**Comment by lwille** [comment]
@jwulf Good morning! Sorry for all the noise, I think I found a fix to the missing `dist` directory :tada:
