### ISSUE TITLE
Discussion: Automatic retries

### ISSUE THREAD

**Issue by jwulf** [creditsenseau/zeebe-client-node-js#35]
At the moment, the client does not automate any retries. This issue is to capture the current behaviour of the client library in various failure scenarios - taken from [here](https://forum.zeebe.io/t/is-grpc-a-point-of-failure-when-embedding-the-workflow-in-a-program/455/8).

## Points of failure client-broker over gRPC

There are three points of contact:

1. **Client initiating an operation on the broker**
* `failJob`
* `publishMessage`
* `createWorkflowInstance`
* `resolveIncident`

2. **Worker activating jobs**
* `activateJobs`

3. **Worker completing / failing job**
* `completeJob`
* `failJob`

## Current Failure Modes

Looking at the current behaviour of each one: 

1. **Client initiating an operation on the broker.**
* If the client is started and the broker is not contactable, any operations will throw.
* If the broker becomes available, operations succeed. 
* If the broker goes away, operations throw again.
* No automatic retries.

2. **Worker activating jobs**
* If the worker is started and the broker is not contactable, an error is printed to the console.
* If the broker becomes available, the worker activates jobs.
* If the broker goes away, no error is thrown or printed.
* If the broker comes back, jobs are activated.
* In this case, the worker polling is an automatic retry.

3. **Worker completing jobs**

* If the broker goes away after the worker has taken a job, the worker throws `Error: 14 UNAVAILABLE` when it attempts to complete the job.
* No automatic retry.

## Ways the broker could go away / be unavailable:

* Broker address misconfigured.
* Transient network failure.
* Broker under excessive load.

**Broker Address Misconfigured**
This is an unrecoverable hard failure. Retries will not fix this.

**Transient network failure**
Some temporary disruption in connectivity between worker and broker. This could include a broker restarting or (potentially) a change in DNS (have to test this).
A retry will deal with this case _if_ the transient network failure is fixed before the retries timeout.

**Broker is under excessive load and cannot respond**
In this case, retries may actually make it worse. Zeebe is horizontally scalable, but I have driven it to failure on a single node by pumping in a massive number of workloads when it is memory starved (I can kill it with 2GB of memory, but haven't yet with 4GB) or runs out of disk space (a slow exporter with a high through-put can do this). Having automated retries will not recover any of these situations.

If the broker is experiencing excessive load because of a traffic spike, then automated retries may drive it to failure, whereas workers failing to complete tasks once and letting the broker reschedule them may allow the broker to recover.

**Other failure modes not distinguished**
The as-yet unknown unknowns. Any ideas?

---
## Conclusions

I'm not yet sure that automatic retry is (a) necessary; (b) a good idea.

The transient network failure seems to be the only case. I'm not sure how much of an issue that is in an actual system, and if it warrants complicating the code, or the potential downside of hammering a broker when it is experiencing excessive load (which will be either ineffective if it is a hard failure, and could contribute to a hard failure if it is a spike).

----
I'm open to more data on this, but I don't have a case for implementing retries yet.

**Comment by jwulf** [comment]
Client-side gPRC load-balancing may be one option (see [here](https://grpc.io/blog/loadbalancing/).

This would look like making the `brokerAddress` an `string|string[]`. If it is an array of broker addresses, then the client lib would implement simple round-robin. If a call fails, it will rotate through the others until one succeeds or they all failed.

We could track which ones are failing, and weight repeated failures to try those gateways less often, then heal it on success.

**Comment by s3than** [comment]
I'd also look at implementing leaky bucket so you can ensure that it's not a straight retry which would resolve the hammering the broker.

Depending on how you want to perform the load balancing though, would introducing it client side bring you back to the complicating the code?

**Comment by jwulf** [comment]
``` The two built-in policies in the gRPC-Go library are the roundrobin and grpclb policies.``` ref: [On gRPC Load-balancing](https://itnext.io/on-grpc-load-balancing-683257c5b7b3)

The underlying node grpc library does support retries, via interceptors (see [here](https://github.com/grpc/grpc-node/issues/284)). To get support for retries via this method would probably involve adding support to (node-grpc-client)[https://www.npmjs.com/package/node-grpc-client]. They are amenable to PRs - I added streaming support there to get it working for the Zeebe client.

**Comment by jwulf** [comment]
> Depending on how you want to perform the load balancing though, would introducing it client side bring you back to the complicating the code?

Yeah, it's a cost/benefit analysis. Have to see where it makes sense to locate load-balancing and whether it makes sense to implement automatic retries.

gRPC load-balancing is usually done with either a client library implementation or some kind of service mesh, like Istio+Envoy. Retries is either automated in the client lib, or the call is failed and it is up to the application to handle it in the context of the business process.

A simple round-robin in the client would be a way to do both load-balancing and a short period retry that handles a gateway failure. It wouldn't give you a long-running retry (for example if the broker goes away ála Google Cloud disappearing or a disk filling up), but in that case you may want the business process to fail fast and handle the failure systemically. 

I think start from a simple round-robin and put in more sophisticated retry behaviour if there is a use-case for it.

**Comment by jwulf** [comment]
Noting for future reference another Node gRPC library that provides a simple linear retry: [grpc-caller](https://github.com/bojand/grpc-caller#Request+withRetry) 

It uses the same interface as [async.retry](https://github.com/caolan/async/blob/v1.5.2/README.md#retry).

Could be a drop-in replacement for node-grpc-client, which would give zeebe-node simple retry for free.

**Comment by jwulf** [comment]
Addressed by #40 based on a concrete use case.
