### ISSUE TITLE
Shelljs vunerability

### ISSUE THREAD

**Issue by s3than** [creditsenseau/zeebe-client-node-js#44]
There's vunerability in shelljs dependency. This is provided by the typedoc package see: https://github.com/TypeStrong/typedoc/issues/1056

shelljs/shelljs@7a9f8e5

Actual behavior:
Typedoc depends on vulnerable package

Expected behavior:
Typedoc doesn't depend on vulnerable package

**Comment by s3than** [comment]
This package is not installed outside a dev dependency

**Comment by jwulf** [comment]
Dev dependency only. Closed WONT_FIX.
