### ISSUE TITLE
Interfaces don't reflect received data and grpc behaviour for "Long" type

### ISSUE THREAD

**Issue by OlivierAlbertini** [creditsenseau/zeebe-client-node-js#49]
## Current behaviour

By default, All fields of type int64 are serialized/desrialized to string instead of number.
Recent interfaces changes have set those fields to number but data are actually string.

## Expected behaviour

Interfaces should reflect what data we have.

## Recommandation

See https://github.com/grpc/grpc/issues/7229. Since int64 are keys, this is not something that we increment. We should stay with default grpc behaviour.
@jwulf recommends to add those fields as `readonly` too.

We don't need to change README because int64 fields are already displayed to string
see:
```
{ key: '578',
  type: 'demo-service',
  jobHeaders:
   { workflowInstanceKey: '574',
     bpmnProcessId: 'test-process',
     workflowDefinitionVersion: 1,
     workflowKey: '3',
     elementId: 'ServiceTask_0xdwuw7',
     elementInstanceKey: '577' },
  customHeaders: '{}',
  worker: 'test-worker',
  retries: 3,
  deadline: '1546915422636',
  variables: { testData: 'something' } }
```

**Comment by jwulf** [comment]
We don't need to change the docs where we already show the type as string, but we should add a note to explain that all protobuf int64 type fields are deserialised as type string in the Node library, because that's a distinct difference from the Go and Java clients.
