### ISSUE TITLE
Add gRPC connection onReady() and onConnectionError() handlers

### ISSUE THREAD

**Issue by jwulf** [creditsenseau/zeebe-client-node-js#71]
While [implementing status in the node-red library](https://github.com/pedesen/node-red-contrib-zeebe/issues/4), the guys report that with 0.20.3, connecting a client to a non-existing broker, then starting a worker, reports that the worker is connected (does not report a broken connection).

**Comment by jwulf** [comment]
This may be due to the connection retry strategy. The ZBClient retries the connection and does not throw.

**Comment by urbanisierung** [comment]
Noticed the same behavior in my implementation. With 0.20.1 I got an connection error, and as soon as a running broker was shut down the onConnectionError handler (as described [here](https://github.com/creditsenseau/zeebe-client-node-js#create-a-task-worker)) was fired.

**Comment by jwulf** [comment]
Yes, it is because of the gRPC retry behaviour.

Otherwise all your workers will explode whenever the nodes are pre-empted in Camunda Cloud, or if the broker is still coming up in docker-compose. 

Not sure how to handle this one...

**Comment by jwulf** [comment]
I have the approach figured out now.

Initially, I will provide as first-class on the ZBClient an `onReady` event that fires whenever a stable connection is achieved, and an `onConnectionError` event that is debounced, and a `connected` property that can be examined.

Each worker has its own gRPC channel, so it possible that a worker created from the client could be in a failed connection state when the client is connected. If that shows up, I'll make it more sophisticated.

**Comment by jwulf** [comment]
Looking into this: no error is caused in the gRPC connection until you try to use it. 

I can put a call to `topology()` in the constructor to provoke a failure...

**Comment by jwulf** [comment]
This commit: https://github.com/jwulf/zeebe-client-node-js/commit/e12db74ae76e566af642434d71ff9490cae32d24 adds to `ZBClient`:

* a boolean `connected` property that makes a statement about the connected status.
* an `onReady()` callback that is called when the client is connected and ready to operate.
* an `onConnectionError()` callback that is called when the client connection fails.

I need to write tests to inspect what happens when a broker goes away after a successful connection.

**Comment by jwulf** [comment]
Looks good when a broker goes away / comes.

I am adding  `onConnection` and `onReady` handlers per-worker in the `createWorker` constructor options (the existing `onConnectionError` trailing param will override one supplied in options).

The workers will inform the client if they detect a failed connection, so unless per-worker behaviour is needed, you can just listen on the client callbacks.

@TODO: add debouncing in the client's listeners, because now they can be called multiple times in succession by the workers.

**Comment by jwulf** [comment]
I added the wiring to bubble up worker errors into the client.

- [ ] test that multiple workers on a client do not cause multiple invocations.

- [ ] test that the workers can have independent onConnectionError handlers and that those work.

@todo: Make sure that business errors (like CREATE failed) do not call the onConnectionError handler.

**Comment by jwulf** [comment]
- [ ] Make sure that business errors (like CREATE failed) do not call the onConnectionError handler.
Update: business errors *do* call this handler :-(

- [ ]  Test that the previous API for attaching an onConnectionError handler to the worker (last param) still works.
