### ISSUE TITLE
Message event error: EXTRACT_VALUE_ERROR

### ISSUE THREAD

**Issue by shantanubhusari** [creditsenseau/zeebe-client-node-js#76]
In my workflow, there is a message event, which should be triggered by the client. I believe I’m sending the correct message to the broker but It’s raising an incidence { "Error Type": "EXTRACT_VALUE_ERROR", "Error Message": "Failed to extract the correlation-key by ‘worker1Id’: no value found" }.

Following is the message event catch:
`<bpmn:message id="Message_01t2tpj" name="worker_status">
    <bpmn:extensionElements>
      <zeebe:subscription correlationKey="worker_Id" />
    </bpmn:extensionElements>
  </bpmn:message>`

Following is the trigger:
`await this._zbClient.publishMessage({
      correlationKey: 'worker_Id',
      messageId: uuid.v4(),
      name: 'worker_status',
      variables: { status: 'PROCESSED' },
      timeToLive: 60000,
    });`

**Comment by jwulf** [comment]
See "Common Mistakes" here: https://zeebe.io/blog/2019/08/zeebe-message-correlation/

Also, refer to this issue: https://github.com/zeebe-io/zeebe/issues/2718
