### ISSUE TITLE
Exporting ZBWorker Class

### ISSUE THREAD

**Issue by OlivierAlbertini** [CreditSenseAU/zeebe-client-node-js#8]
Hi,

I made a [PR](https://github.com/CreditSenseAU/zeebe-client-node-js/pull/7) in order to get the type ZBWorker. Since my app is developed in Typescript, It would be useful.

vscode targets to dist folder which is not safe.

Let me know if you need anything else. Thanks!

**Comment by jwulf** [comment]
Great - thanks!

**Comment by jwulf** [comment]
I published 1.0.5, which includes this patch.
