### ISSUE TITLE
Long Polling workers do not reconnect if broker goes away then comes back

### ISSUE THREAD

**Issue by jwulf** [creditsenseau/zeebe-client-node-js#82]
During Kubernetes node pre-emption, I've observed workers failing to reconnect.

I'd say that somewhere in the long-polling loop is a condition that does not trigger the poll retry in this scenario.

Fixing this will involve setting up - at least local - tests where the broker is bounced. This will be more challenging to simulate in CI, but should not be a blocker for this fix, because it is a critical production failure.

**Comment by jwulf** [comment]
Watching my systems in Camunda Cloud, they do seem to reconnect after some time, so it may be the exponential back-off retry causing a delay after the cluster recovers.

**Comment by pedesen** [comment]
I experience the same, when I connect a Node-RED worker node to Camunda Cloud (stage environent). Sometimes   they're disconnected for minutes, but eventually get reconnected.

**Comment by jwulf** [comment]
This seems to happen when the cluster pods are rescheduled, and the reconnection backs-off. Maybe a switch for aggressive retry?

**Comment by jwulf** [comment]
Some of these scenarios will be dealt with via #96

**Comment by pedesen** [comment]
I can confirm, that https://github.com/creditsenseau/zeebe-client-node-js/issues/96 fixes my issue

**Comment by jwulf** [comment]
It looks like the issue is a combination of two things: the issue fixed in #96, and Camunda Cloud terminating the gRPC connection to nginx after 60s. That caused clients with >59s long-polling periods to encounter the issue fixed in #96 if they did not receive any jobs within 60s.

Closing for now. Reopen if it appears again.
