### ISSUE TITLE
onReady is not called initially for workers

### ISSUE THREAD

**Issue by pedesen** [creditsenseau/zeebe-client-node-js#97]
When I create a worker like this:
```js
zbc.createWorker(
  null,
  'demo-service',
  handler,
  {
    onReady: () => console.log(`Worker connected!`),
    onConnectionError: () => console.log(`Worker disconnected!`),
  }
)
```

then onReady is not called initially after creating the worker. I only gets called, when a connection error happened before.

**Comment by jwulf** [comment]
We don't have tests yet that can test with a broker appearing/disappearing. Have you tested this against a local broker bringing it up and down to see how it performs?

**Comment by jwulf** [comment]
Yep, this works. Added the patch with a test.
